language: go
go:
    - 1.5
    - 1.6
    - tip
before_install:
    - export PATH=$PATH:$GOPATH/bin
    - go get github.com/modocache/gover
    - go get github.com/mattn/goveralls
    - go get golang.org/x/tools/cmd/cover
install:
    - go get -u github.com/jteeuwen/go-bindata/...
    - go-bindata -o template/assets/templates.go -pkg=assets_test -prefix=template/testdata/loader template/testdata/loader/...
    - go get -t -v ./...
script:
    - diff -u <(echo -n) <(gofmt -d -s $(find . -type f -name '*.go' -not -path "./template/assets/*"))
    - go test -coverprofile=log.coverprofile ./log
    - go test -coverprofile=template.coverprofile ./template
    - go test -coverprofile=middleware.coverprofile ./middleware
    - gover
    - goveralls -coverprofile=gover.coverprofile -service=travis-ci
matrix:
  allow_failures:
    - go: tip